### ISSUE TITLE
Firefox mobile Android

### ISSUE THREAD

**Issue by reeslo** [cferdinandi/scrollStop#1]
Notice working well on firefox mobile

**Comment by reeslo** [comment]
Not

**Comment by cferdinandi** [comment]
Could you be a bit more descriptive, include and screen cast or animated screenshot… This is pretty nonspecific.

**Comment by reeslo** [comment]
Try with Firefox mobile on Android, while scrolling on your demo page, is alerte bombing saying scrolling end.

**Comment by cferdinandi** [comment]
Ahh... Looks like I accidentally pushed an alert up to the live demo site. Will fix. Thanks!

**Comment by cferdinandi** [comment]
I looked at this fast and thought it was for another plugin of mine. This is the expected behavior on the demo page. It triggers an alert when scrolling ends.
