### ISSUE TITLE
listeniing to div scrollstop

### ISSUE THREAD

**Issue by davidkutas** [cferdinandi/scrollStop#2]
Would it be somehow possible to rewrite the code to be able to listen to scrollstop function inside a div, instead of window or document? I tried to rewrite here:

...`window.addEventListener(`....

but no luck!

**Comment by cferdinandi** [comment]
Not possible with this snippet, but these two look promising:

1. https://stackoverflow.com/a/5535922/1293256
2. http://qnimate.com/detecting-end-of-scrolling-in-html-element/

I haven't tested either of them.
